### ISSUE TITLE
Cocoapods compile error

### ISSUE THREAD

**Issue by bretdabaker** [kean/DFCache#2]
`CGFloat` is used in `DFDiskCache.h` and `DFValueTransformer.h` but `<CoreGraphics/CoreGraphics.h>` is not imported in any of the headers. So when I compile my project with the pod, it shows an error that definition of `CGFloat` is not found. 

Right now I have to import `<CoreGraphics/CoreGraphics>` in my own source files in order to get rid of the error.

Since `CGFloat` is part of `<CoreGraphics/CoreGraphics>` and is generally drawing related, I would suggest you use `float` instead.

**Comment by kean** [comment]
Good idea, thanks.

**Comment by kean** [comment]
Fixed in 6881bb9e4afc27c2ccb55317e36389474df4c84d
