### ISSUE TITLE
Cache not persistent across app launches

### ISSUE THREAD

**Issue by frankdilo** [kean/DFCache#6]
Hi, thanks a lot for this wonderful library. It is really a pleasure to use.

I am writing to you because I may have found an issue and wasn't able to help myself by looking at your code or the documentation. In short, it is not clear to me when the cache is written to disk. I would expect this to happen periodically or at app termination, but from my tests this does not seem to be the case.

The example I set up is an OS X application, and I am pretty much using your [first example](https://github.com/kean/DFCache#store-retrieve-and-remove-object). I launch the app, write to the cache with key "abc", read from the cache with key "abc" (hit), close the app, open the app, read from the cache with key "abc" (miss).

Any clue what might be going on? (I also tried waiting 60 seconds before closing the app).

**Comment by kean** [comment]
Hi, I'm glad that you find it useful. 

I personally haven't used this library for a long time so I probably won't be able to help you debug this issue. I also don't have much experience with OS X. It's a very small project, I think that you won't run into much trouble debugging it. I would be glad to answer any concerte questions though.

**Comment by frankdilo** [comment]
Ok, I'll try debugging this myself and submit a PR if I find anything wrong. Could you explain to me what's your policy when dumping the cache to disk? Do you do this periodically or is there something else involved?

**Comment by kean** [comment]
> Could you explain to me what's your policy when dumping the cache to disk? Do you do this periodically or is there something else involved?

DFCache writes to disk right away, see `-[DFCache storeObject:forKey:]`. It's all very straightforward, except maybe for the `object ~> data` transformation part.

I suspect that there might be some issues with the default directory used for cache (see `-[DFDiskCache cachesDirectoryPath]`). It might behave differently on OS X compared to iOS.

**Comment by frankdilo** [comment]
Thanks, I will investigate and report back! 👍
